## -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.8.0"

Vagrant.configure("2") do |config|

	config.vm.define "d2l2web" do |d2l2web|
		d2l2web.ssh.forward_agent = true
		d2l2web.vm.box = "scotch/box"
		d2l2web.vm.network :private_network, ip: "192.168.100.30"
		d2l2web.vm.hostname = "d2l2web.local"
        d2l2web.vm.synced_folder ".", "/vagrant", :mount_options => ["dmode=755","fmode=644"]
		d2l2web.vm.synced_folder "../d2l2", "/var/www/html", create: true

		d2l2web.vm.provider :virtualbox do |vb|
			vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
			vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
			vb.name = "d2l2web"
			vb.customize ["modifyvm", :id, "--cpus", 2]
			vb.customize ["modifyvm", :id, "--memory", 2048]
			vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
			vb.customize ["modifyvm", :id, "--ioapic", "on"]
			vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
		end

		# Run Ansible from the Vagrant VM
		d2l2web.vm.provision "ansible_local" do |ansible|
			ansible.provisioning_path = "/vagrant/ansible/"
			ansible.inventory_path = "/vagrant/ansible/inventory/development"
			ansible.playbook = "vagrant_install.yml"
#			ansible.verbose = "vvv"
			ansible.limit = "local"
			ansible.vault_password_file="/vagrant/ansible/dev-vault"
		end
	end
end
